<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <AssemblyName>ReWrite</AssemblyName>
    <RootNamespace>ReWrite</RootNamespace>
    <Product>ReWrite</Product>
    <Authors>Huynh Nam Duy</Authors>
    <Copyright>© 2026 Huỳnh Nam Duy</Copyright>
    <AssemblyTitle>ReWrite</AssemblyTitle>
    <ApplicationIcon>ui\logo.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>

    <Version>0.0.$([System.DateTime]::Now.ToString("yyMMdd"))</Version>

    <AssemblyVersion>1.0.0.0</AssemblyVersion>

    <FileVersion>0.0.$([System.DateTime]::Now.DayOfYear).$([System.DateTime]::Now.Minute)</FileVersion>

    <InformationalVersion>build-$([System.DateTime]::Now.ToString("yyyyMMddHHmmss"))</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Page Include="Windows\MainWindow\MainWindow.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Page Include="Windows\PopupWindow\PopupWindow.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Page Include="Windows\SettingsWindow\SettingsWindow.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Page Include="Windows\TutorialWindow\TutorialWindow.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Page Include="Windows\WelcomeWindow\WelcomeWindow.xaml" SubType="Designer" Generator="MSBuild:Compile" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="App.xaml.cs" DependentUpon="App.xaml" />
    <Compile Update="Windows\MainWindow\MainWindow.xaml.cs" DependentUpon="MainWindow.xaml" />
    <Compile Update="Windows\PopupWindow\PopupWindow.xaml.cs" DependentUpon="PopupWindow.xaml" />
    <Compile Update="Windows\SettingsWindow\SettingsWindow.xaml.cs" DependentUpon="SettingsWindow.xaml" />
    <Compile Update="Windows\TutorialWindow\TutorialWindow.xaml.cs" DependentUpon="TutorialWindow.xaml" />
    <Compile Update="Windows\WelcomeWindow\WelcomeWindow.xaml.cs" DependentUpon="WelcomeWindow.xaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ui\**\*" />
    <EmbeddedResource Include="Windows\**\*.html" />
    <EmbeddedResource Include="Windows\**\*.js" />
    <EmbeddedResource Include="Windows\**\*.css" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\Localization\locales\**\*.json" />
  </ItemGroup>
</Project>
