name: Auto Build & Release ReWrite

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Compile Tailwind CSS
        run: npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -r win-x64 -o release

      - name: Get version
        id: version
        run: |
          $exe = "release/ReWrite.exe"
          $version = (Get-Item $exe).VersionInfo.FileVersion
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Rename EXE
        run: |
          $version = "${{ steps.version.outputs.VERSION }}"
          Rename-Item "release/ReWrite.exe" "ReWrite-Portable-v$version.exe"

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ReWrite.iss
          options: "/DAppVersion=${{ steps.version.outputs.VERSION }} /Oinstaller /FReWrite-Setup-v${{ steps.version.outputs.VERSION }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: ReWrite v${{ steps.version.outputs.VERSION }}
          files: |
            release/ReWrite-Portable-v${{ steps.version.outputs.VERSION }}.exe
            installer/ReWrite-Setup-v${{ steps.version.outputs.VERSION }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}